### ISSUE TITLE
findLogPath returns wrong path

### ISSUE THREAD

**Issue by samsamm777** [megahertz/electron-log#114] opened 2019-02-22 11:42 UTC
Version: "electron-log": "3.0.1"

When calling `findLogPath` it returns the application support directory and not the logs directory path.

`const p = log.transports.file.findLogPath('appname');`
returns:
/Users/username/Library/Application Support/appname/log.log
should be:
/Users/username/Library/Logs/appname/log.log

**Comment by megahertz** [comment] 2019-02-22 12:04
What is the output of `ls -l ~/Library/Logs`?

**Comment by samsamm777** [comment] 2019-02-25 14:10
It outputs my logs directory. There is a directory in there which is my app name, which contains the logfile im looking for.

**Comment by megahertz** [comment] 2019-02-25 17:04
It's strange things. I'll try to reproduce the bug on this week. Which Electron version do you use?

**Comment by samsamm777** [comment] 2019-03-13 09:02
@megahertz Any luck reproing this?

**Comment by megahertz** [comment] 2019-03-13 10:07
@samsamm777 I can't reproduce this problem. I'll try to investigate this problem later, since I have no time for it now. You could create a simple project which reproduce the problem, it allows me to fix it much faster.

**Comment by megahertz** [comment] 2019-11-20 15:23
Fixed in v4

**Closed by megahertz** 2019-11-20 15:23 UTC
