### ISSUE TITLE
main process catches errors from the renderer process even though it has its own catch function

### ISSUE THREAD

**Issue by gozzoo** [megahertz/electron-log#123] opened 2019-03-25 11:47 UTC
I'd like each process to catch only its own errors. I have disabled cross process logging as suggested in #122

Here is my code:

`main.js`

```
function onError(error) {
  log.error(error)
  return false
}

log.transports.rendererConsole.level = false
log.catchErrors({onError})
```

`renderer.js`

```
function onError(error) {
  log.error(error)
  return false
}

log.transports.mainConsole.level = false
log.catchErrors({onError})

throw new Error('hello')
```

What is strange is that I don't get in the console of the main process the message of the error and it shows up 3 times.

```
Error {}
Error {}
Error {}
```

**Comment by gozzoo** [comment] 2019-03-25 11:51
I'd like each process to catch only its own errors. I have disabled cross process logging as suggested in #122

Here is my code:

`main.js`

```
function onError(error) {
  log.error(error)
  return false
}

log.transports.rendererConsole.level = false
log.catchErrors({onError})
```

`renderer.js`

```
function onError(error) {
  log.error(error)
  return false
}

log.transports.mainConsole.level = false
log.catchErrors({onError})
```

**Comment by megahertz** [comment] 2019-03-25 13:03
Thanks for the report. I'll check it a bit later.

**Comment by megahertz** [comment] 2019-03-27 08:58
Could you please share a simple example project? I can't reproduce the problem.

**Comment by gozzoo** [comment] 2019-03-27 11:37
I also couldn't reproduce it in a simple project. I'll have to dig deeper to find out what's going on. My app is using IPC, may be there is some interference.

**Comment by megahertz** [comment] 2019-11-20 15:29
I think it should be fixed in v4. Please let me know if it still appears.

**Closed by megahertz** 2019-11-20 15:29 UTC
